### ISSUE TITLE
Add project: putty

### ISSUE THREAD

**Issue by njsmith** [mahmoud/zerover#10]
## Basic info

**Project name**: Putty
**Project link**: https://www.chiark.greenend.org.uk/~sgtatham/putty/

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [x] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Citation info

https://en.wikipedia.org/wiki/PuTTY

Initial release: January 8, 1999; 19 years ago
Stable release: **0.70** / July 8, 2017; 8 months ago

---

**Comment by njsmith** [comment]
Ugh, you confused me with your sorta-alphabetical-looking-but-not-really table! (That's my story anyway and I'm sticking to it.)

**Comment by mahmoud** [comment]
Haha, gotta play with those sortable columns! Still, thank you for the well-formatted issue all the same!
