### ISSUE TITLE
Add project: OpenRC

### ISSUE THREAD

**Issue by cschmatzler** [mahmoud/zerover#100]
## Basic info

**Project name**: OpenRC 
**Project link**: https://github.com/OpenRC/openrc

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [ ] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [x] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

Used in Alpine Linux, Gentoo, different BSD versions.

**Comment by MattTheCuber** [comment]
This has been added and can be closed

**Comment by MattTheCuber** [comment]
@mahmoud this, #107, #121, and #133 can all be closed.
