### ISSUE TITLE
Add project: Notary (i.e. the component that implements Docker Content Trust)

### ISSUE THREAD

**Issue by robmoore-i** [mahmoud/zerover#107]
## Basic info

**Project name**: Notary
**Project link**: https://github.com/notaryproject/notary

Current version: 0.6.1

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [x] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [x] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

Notary is the service that provides Docker Content Trust i.e. image signing. It is a very important infrastructure component. Many companies require the use of Docker Content Trust as a matter of course.

And then look at this, from the Docker documentation:

<img width="994" alt="Screenshot 2021-10-18 at 12 03 18 PM" src="https://user-images.githubusercontent.com/1451027/137667588-ab7df66a-9c55-4bb2-bac2-40a5ecd6f573.png">

UGH

## Additional notability info

- Docker
- Azure Container Registry
- The managed Harbor registry service (i.e. https://container-registry.com)
- So much more

## Citation info

(left blank)

---

**Comment by MattTheCuber** [comment]
This has been added and can be closed
