### ISSUE TITLE
Add project: XeTeX

### ISSUE THREAD

**Issue by Pomax** [mahmoud/zerover#115]
## Basic info

**Project name**: XeTeX
**Project link**: http://xetex.sourceforge.net, https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=xetex
**Current version**: 0.999992 as of 2020-01-20 

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version and long history of ZeroVer usage
- [x] Very wide exposure (part of TeX Live and MiKTeX)
- [x] Active promotion by SIL, the same folks behind the web open font license
- [x] Mature for a long time now, and infrastructurally important in the TeX world

## Additional notability info

It's XeTeX.

## Citation info

---

**Comment by mahmoud** [comment]
Nice! So, for off-GitHub projects like this one, we need to manually collect the following metadata:

1. First release version
2. First release date

Thanks!

**Comment by Pomax** [comment]
You bet - as per http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&item_id=xetex_history&_sc=1 the first release used version 0.3, on 2004-04-07 (april 7th, not july 4)
