### ISSUE TITLE
Add project: Fabric API

### ISSUE THREAD

**Issue by SilverAndro** [mahmoud/zerover#133]
## Basic info

**Project name**: Fabric API
**Project link**: https://github.com/FabricMC/fabric

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [ ] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

Fabric API is the main API for modding minecraft with the fabric toolchain. Although technically optional its essentially mandatory due to the large collection of mods depending on it, having over 36 million downloads on curseforge  (currently the main platform for minecraft mod hosting on the english speaking side of the internet). Its first release on curseforge was on Dec 9, 2018, giving it almost 4 years of mainline ZeroVer usage.

## Citation info
https://www.curseforge.com/minecraft/mc-mods/fabric-api - Main download page
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/2645894 - First curseforge release

**Comment by MattTheCuber** [comment]
This has already been added and can be closed.
