### ISSUE TITLE
Add project: Woodpecker CI

### ISSUE THREAD

**Issue by Jackenmen** [mahmoud/zerover#135]
## Basic info

**Project name**: Woodpecker CI
**Project link**: https://github.com/woodpecker-ci/woodpecker

## Qualifications

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [ ] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

- Quite a popular project in self-hosted Git hosting, i.e. people can self-host their CI pipeline and integrate it with Gitea
    - Integration with other platforms such as GitHub, GitLab, or Bitbucket is also present
- People using Woodpecker CI:
https://github.com/woodpecker-ci/woodpecker/issues/122
- [Codeberg](https://codeberg.org/) uses Woodpecker CI in the closed testing phase of their CI system.

## Citation info

First release of Woodpecker was on April 6, 2019: https://github.com/woodpecker-ci/woodpecker/releases/tag/v0.8.91

**Comment by 6543** [comment]
haha nice try :)

https://github.com/woodpecker-ci/woodpecker/milestones

at some point it's non ZeroVersioning but SemVersioning

**Comment by jack1142** [comment]
You're not the only one that *plans* to eventually make 1.0, I imagine almost everyone does ;)

**Comment by 6543** [comment]
outdated :D https://github.com/woodpecker-ci/woodpecker/releases/tag/v1.0.0

**Comment by Jackenmen** [comment]
Maybe it could be put on emeriti list but I don't really care for it so I'll just close.
