### ISSUE TITLE
mypy finally reached 1.0.0

### ISSUE THREAD

**Issue by trag1c** [mahmoud/zerover#147]
https://github.com/python/mypy/tags

**Comment by steve-mavens** [comment]
Some of us are keeping the faith, and pinning mypy <1.0. In my case because of another pin, to pydantic 1.9.*, which relied on mypy's 0ver status to the extent of using `float()` to parse the version number in a compatibility check. I'm not even lying.

**Comment by mahmoud** [comment]
MyPy has joined [the emeriti](https://0ver.org/#selected-emeriti) after 0nly 8 years. Such a shame ;) Thanks for the heads up!
