### ISSUE TITLE
Add project: rollup

### ISSUE THREAD

**Issue by AlexLandau** [mahmoud/zerover#15]
## Basic info

**Project name**: rollup
**Project link**: https://github.com/rollup/rollup and https://rollupjs.org/guide/en

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [ ] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

Rollup is a build tool used (per [this article](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c)) by many prominent projects in the JS ecosystem, including React, Vue, Ember, Preact, D3, Three.js, and Moment. It is generally promoted as the future of building JavaScript libraries.

**Comment by mahmoud** [comment]
Looks like I slept on this one. Rollup is definitely a big deal, I should look at adding it to the emeriti bc it's only been >1.0 for the last year or so. Belated thanks!
