### ISSUE TITLE
Add project: pipewire

### ISSUE THREAD

**Issue by glyph** [mahmoud/zerover#151]
## Basic info

**Project name**: PipeWire
**Project link**: https://pipewire.org

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage ([currently 0.3.70](https://github.com/PipeWire/pipewire/releases/tag/0.3.70)), and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [x] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

From the website: 

> Alongside Wayland and Flatpak, we expect PipeWire to provide a core building block for the future of Linux application development.

https://en.wikipedia.org/wiki/PipeWire

This paragraph is particularly notable:

> In April 2021, [Fedora Linux](https://en.wikipedia.org/wiki/Fedora_Linux) 34 became the first [Linux](https://en.wikipedia.org/wiki/Linux) distribution to ship PipeWire for audio by default.[[14]](https://en.wikipedia.org/wiki/PipeWire#cite_note-14)[[15]](https://en.wikipedia.org/wiki/PipeWire#cite_note-15)[[16]](https://en.wikipedia.org/wiki/PipeWire#cite_note-16) A year later, [Pop! OS](https://en.wikipedia.org/wiki/Pop!_OS) adopted it as the default audio server in version 22.04.[[17]](https://en.wikipedia.org/wiki/PipeWire#cite_note-17) It was made the default audio server in [Ubuntu](https://en.wikipedia.org/wiki/Ubuntu) beginning with version 22.10.[[18]](https://en.wikipedia.org/wiki/PipeWire#cite_note-18)

## Citation info

---

**Comment by glyph** [comment]
thanks!

**Comment by mahmoud** [comment]
Of course! A 22.04 user myself, let me tell you, I am not the least bit surprised to learn this. 11,000 commits! That's dedication to the 0ver cause.
