### ISSUE TITLE
Add Project: MultiMC

### ISSUE THREAD

**Issue by brianaohern** [mahmoud/zerover#152]
## Basic info

**Project name**: MultiMC
**Project link**: [https://multimc.org/posts/0-7-0-update.html](https://multimc.org/posts/0-7-0-update.html) / [https://github.com/MultiMC/Launcher](https://github.com/MultiMC/Launcher)

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [x] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

Prominent launcher for maintaining multiple instances of MineCraft, (i.e. different instances with different modpacks, versions, etc.)

## Citation info

---

**Comment by mahmoud** [comment]
Nice, thanks!
