### ISSUE TITLE
Add project: monero

### ISSUE THREAD

**Issue by MrCyjaneK** [mahmoud/zerover#153]
## Basic info

**Project name**: monero
**Project link**: https://github.com/monero-project/monero

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [x] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

**Comment by mahmoud** [comment]
m0re like m0ner0, eh? Added, thanks!
