### ISSUE TITLE
Add project: bytestring

### ISSUE THREAD

**Issue by jamestmartin** [mahmoud/zerover#186]
## Basic info

**Project name**: bytestring
**Project link**: https://hackage.haskell.org/package/bytestring
**GitHub link**: https://github.com/haskell/bytestring
Current version: 0.12.1.0, released 2024-02-16

## Qualifications

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [ ] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [x] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

* ByteString is one of the most important foundational packages in the Haskell ecosystem.
* Almost every non-trivial program depends on it, alongside over 8000 libraries.
* It's shipped with the compiler.

Essentially any time you do any I/O in Haskell more sophisticated than `putStrLn`, you are directly or indirectly depending on bytestring.

## One more thing

The main reason I don't make a PR myself is that I can't tell how old it is.

* The oldest release on Hackage was in 2007, but that's already version 0.9.
* The git commit history only goes back to 2005, because it used a different version control system before that.
* The copyright dates back to at least 2003.
* Additionally, do FastPackedString (or PackedString) count as previous releases of this project, or should bytestring be considered a fork?

**Comment by mahmoud** [comment]
Haha that's an 0ver project if there's ever been one. As far as dating it, I think the 2007 date is probably old enough to get the point across. At some point the 0ver builder might grow the ability to override GitHub metadata, but for now I've just added the above as comments :)
