### ISSUE TITLE
Add project: Discord for Linux and macOS

### ISSUE THREAD

**Issue by hutli** [mahmoud/zerover#191]
## Basic info

**Project name**: Discord (for Linux and macOS)
**Project link**:  <https://discord.com/>

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning scheme can obviously be used by everyone, but not every usage is necessarily notable. Check that the first and at least one other criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [x] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [ ] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

Discord is a very popular communication platform with 200+ million monthly users. While it is far from open-source and is very commercial; it does allow custom bots to interact quite in-depth with the platform through a well-documented API. It is quite customizable in terms of creating communities and has excellent moderation tools. However, Discord does not support any level of self-hosting, federation, or even built-in end-to-end encryption. All information sent on the platform is entirely unencrypted (except standard client-server encryption) and stored on Discord's servers, so use it with discretion.

## Citation info

Discord is probably quite an unusual addition to 0ver, as it is closed-source and very commercial. I completely understand if this issue is closed without Discord being added. However, I do find it quite novel that they are so public with their release versioning, especially across all the different operating systems, despite their "close-source-ness."

This issue refers specifically to Discord for **Linux** and **macOS**. The current release versions of all applications are:
- Linux: [0.0.66](https://dl.discordapp.net/apps/linux/0.0.66/discord-0.0.66.tar.gz)
- macOS: [0.0.317](https://dl.discordapp.net/apps/osx/0.0.317/Discord.dmg)
- Windows: [1.0.9159](https://dl.discordapp.net/distro/app/stable/win/x64/1.0.9159/DiscordSetup.exe)
- iOS/iPhone: [244.0](https://apps.apple.com/us/app/discord-talk-play-hang-out/id985746746)
- Android [244.13 (Stable)](https://play.google.com/store/apps/details?id=com.discord)

**Comment by crazo7924** [comment]
I second this

**Comment by mahmoud** [comment]
l0l would love to see this. 0ver works for all sources, whether they're 0pen or cl0sed.

To add non-GitHub projects, we just need the fields added manually to the yaml file, like this: https://github.com/mahmoud/zerover/blob/f4251c2cf16ce6923f5d702887a8011ebc659b25/projects.yaml#L620-L626

**Comment by hutli** [comment]
Amazing! I've created a [pull request](#203), hope it has all the information needed

**Comment by mahmoud** [comment]
> Amazing! I've created a [pull request](https://github.com/mahmoud/zerover/pull/203), hope it has all the information needed

It sure did! These are up on the site now: https://0ver.org/ Thanks!
