### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [mahmoud/zerover#2]
[The official zerover webpage](https://0ver.org/about.html) is inaccessible over IPv6.

**Comment by mahmoud** [comment]
Not much an ipv6 devotee myself, but switched providers a while back, and now I can do:

```
$ dig +short AAAA 0ver.org
2600:3c02::f03c:92ff:febb:1083
```

Which I think puts this to bed. Thanks for your patience.

**Comment by tambry** [comment]
Unfortunately the web server doesn't seem to be listening for IPv6 connections:
```
> curl 0ver.org/
*   Trying 2600:3c02::f03c:92ff:febb:1083...
* TCP_NODELAY set
* connect to 2600:3c02::f03c:92ff:febb:1083 port 80 failed: Connection refused
* Failed to connect to 0ver.org port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 0ver.org port 80: Connection refused
```

If you're using Nginx don't add `listen [::]:443 ssl http2;` and `listen [::]:80;` next to your already existing listen directives (and reload using `nginx -s reload`).

**Comment by mahmoud** [comment]
Server restarted. Honestly, I've always wondered how you ran across this issue. Two years on, I've never heard of anyone not being able to access the site, practically. End users don't have to sweat the stack. Kinda echoing https://apenwarr.ca/log/20170810 I guess.
