### ISSUE TITLE
Honorable mention (hardware)

### ISSUE THREAD

**Issue by maidenone** [mahmoud/zerover#20]
## Basic info
A generic NRF52 sensor node

**Project name**:
Sensor Node
**Project link**:
https://www.aliexpress.com/item/New-products-NRF52832-52810-Hand-Ring-Development-Board-Bluetooth-4-04-1BLE-Nine-Axis-Motion-Sensor/33023947425.html?spm=2114.search0104.3.79.d0a17672Bm7SzT&ws_ab_test=searchweb0_0,searchweb201602_7_10065_10068_319_10546_10059_10884_317_10548_10887_10696_321_322_10084_453_10083_454_10103_10618_10307_10820_10303_537_536,searchweb201603_53,ppcSwitch_0&algo_expid=4ed8e7e2-c34d-4ab3-a387-7b92ef26bebf-12&algo_pvid=4ed8e7e2-c34d-4ab3-a387-7b92ef26bebf&transAbTest=ae803_5

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [ ] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [x] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [x] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

They are selling a product with version 0.0
## Citation info

---

**Comment by mahmoud** [comment]
Hahaha, late reply, but this is hilarious. I'll have to find a way to work that into the prose :)
