### ISSUE TITLE
Add project: wkhtmltopdf

### ISSUE THREAD

**Issue by jesseli2002** [mahmoud/zerover#25]
## Basic info

**wkhtmltopdf**:
**https://wkhtmltopdf.org/**:

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [ ] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

I found out about it since it's mentioned as a PDF engine in Pandoc: https://pandoc.org/MANUAL.html#creating-a-pdf

## Citation info

---

**Comment by mahmoud** [comment]
Fixed in #26 :)
