### ISSUE TITLE
Add React Native to Notable ZeroVer Projects

### ISSUE THREAD

**Issue by kylevdr** [mahmoud/zerover#37]
I have noticed the glaring omission of what would be the most popular ZeroVer project with over 84,900 stars on GitHub: React Native.

Developed by FaceBook and first released in 2015, React Native is currently on version 0.61.5.

github link: [React Native](https://github.com/facebook/react-native)

**Comment by mahmoud** [comment]
How funny, I just got a message yesterday to add it: https://github.com/mahmoud/zerover/commit/607621c38ba4dd05344ecd2653793104423a514b

I published it to 0ver.org just now. The top-ranking project in terms of stars (the only metric that matters™) :smile:

**Comment by mahmoud** [comment]
Fun fact: React itself was 0ver for 2.8 years, looks like React Native is aiming to double it.
