### ISSUE TITLE
Add project: dep

### ISSUE THREAD

**Issue by JelteF** [mahmoud/zerover#4]
## Basic info

**Project name**: dep
**Project link**: https://github.com/golang/dep

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [ ] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Citation info

---

**Comment by mahmoud** [comment]
It's a bit on the young side at only 9 months since the first 0ver release, but given the number of stars and also the first line ("**dep is safe for production use**"), I think this is exactly what 0ver is all about :) Added and published. Thanks!
