### ISSUE TITLE
TOML no longer 0ver compliant

### ISSUE THREAD

**Issue by jesseli2002** [mahmoud/zerover#40]
They've moved away to 1.0.0-rc.1 (Released April 1, although it doesn't seem to be a distasteful April Fools joke).

**Comment by mahmoud** [comment]
Hehe, yeah the CI picked it up. I pushed the new data, they're in the Emeriti. I'll have to update the text at some point.

**Comment by mahmoud** [comment]
Thanks for the heads up though! Good on you for keeping up!
