### ISSUE TITLE
Add project: StreamEx

### ISSUE THREAD

**Issue by amaembo** [mahmoud/zerover#43]
## Basic info

**Project name**: StreamEx
**Project link**: https://github.com/amaembo/streamex

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [ ] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Citation info

---

**Comment by mahmoud** [comment]
Sure looks 0ver to me! Added, with much thanks!
