### ISSUE TITLE
Add project: 3proxy

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [mahmoud/zerover#44]
## Basic info

**Project name**: 3proxy
**Project link**: https://github.com/z3APA3A/3proxy

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x ] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x ] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [ ] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Citation info

---

**Comment by mahmoud** [comment]
good find, thanks! will be published to 0ver.org shortly.
