### ISSUE TITLE
Remove project: Inkscape

### ISSUE THREAD

**Issue by xobs** [mahmoud/zerover#45]
## Basic info

**Project name**: Inkscape
**Project link**: https://inkscape.org/

## Qualifications

Inkscape release v1.0 on 1 May 2020.

## Citation info

Release notes for v1.0 [are available on the Inkscape wiki](https://wiki.inkscape.org/wiki/index.php/Release_notes/1.0).

**Comment by mahmoud** [comment]
No project ever really gets removed, but Inkscape has joined the emeriti: https://0ver.org/#selected-emeriti

Thanks!
