### ISSUE TITLE
Remove project: Windows Terminal

### ISSUE THREAD

**Issue by xobs** [mahmoud/zerover#46]
#42  Basic info

**Project name**: Windows Terminal
**Project link**: https://github.com/Microsoft/Terminal

## Citation info

Windows Terminal 1.0 was released on [19 May 2020](https://devblogs.microsoft.com/commandline/windows-terminal-1-0/).

**Comment by mahmoud** [comment]
Well, nothing ever really gets removed; but the script has picked up the new release and Windows Terminal has graduated: https://0ver.org/#selected-emeriti
