### ISSUE TITLE
Add project: goreleaser

### ISSUE THREAD

**Issue by greut** [mahmoud/zerover#48]
## Basic info

**Project name**: goreleaser
**Project link**: https://goreleaser.com/

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [ ] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Citation info

---

**Comment by mahmoud** [comment]
The irony makes this a very powerful addition, kud0s! Looks like [it's on GitHub](https://github.com/goreleaser/goreleaser/), makes it pretty easy to PR if you're up for it. Just two lines, [like this](https://github.com/mahmoud/zerover/blob/4eeba83b2cab70fdc0e3adb6a79bd4bee071d5b3/projects.yaml#L36-L37). In any case, thanks again!
