### ISSUE TITLE
Add project: Prosody IM

### ISSUE THREAD

**Issue by mwild1** [mahmoud/zerover#5]
## Basic info

**Project name**: Prosody IM
**Project link**: https://prosody.im/

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [X] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [X] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [X] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

Prosody is a widely used server implementation on the XMPP network, with many thousands of deployments. It is packaged in many distros from OpenWRT to Ubuntu.

Prosody has been proudly following ZeroVer for over 9 years.

## Citation info

First release of 0.1.0 in 2008: https://prosody.im/doc/release/0.1.0

Latest release of 0.10.0 in 2017: https://prosody.im/doc/release/0.10.0

**Comment by mahmoud** [comment]
excellent, thank you!
