### ISSUE TITLE
Add project: iodine

### ISSUE THREAD

**Issue by yarrick** [mahmoud/zerover#50]
## Basic info

**Project name**: iodine 
**Project link**: https://github.com/yarrick/iodine

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [ ] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Citation info

---

**Comment by mahmoud** [comment]
Ah, a proud user appears :) With GitHub projects you can self-declare in [a two-line PR like so](https://github.com/mahmoud/zerover/pull/51/files). Care to give it a g0?
