### ISSUE TITLE
Add project: Dwarf Fortress

### ISSUE THREAD

**Issue by NoahTheDuke** [mahmoud/zerover#6]
## Basic info

**Project name**: Dwarf Fotress
**Project link**: http://www.bay12games.com/dwarves/

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [ ] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [x] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

Tarn's opinion is that 1.0 will be reached when the game accurately simulates reality, so I think this is a prime candidate for 0ver.

## Citation info

Wiki page: https://en.wikipedia.org/wiki/Dwarf_Fortress

**Comment by mahmoud** [comment]
Ah, ☼real dwarven zerover goodness☼, thanks!
