### ISSUE TITLE
TOML no longer 0ver 😔

### ISSUE THREAD

**Issue by a-recknagel** [mahmoud/zerover#60]
See https://github.com/toml-lang/toml/releases/tag/1.0.0, they were deceived.

**Comment by a-recknagel** [comment]
As noted in the PR, it would be nice to have an updated text on TOML in the "Featured Use Cases". What do,  @mahmoud ? Should I give it a try, or do you?

**Comment by a-recknagel** [comment]
Also, I'm not familiar with chert. Is there a way to inspect the html that would be built given my change? Just to be sure I didn't screw up.

**Comment by Hans5958** [comment]
This issue should be closed, eh?
