### ISSUE TITLE
Add project: elm-lang

### ISSUE THREAD

**Issue by tom-lord** [mahmoud/zerover#73]
## Basic info

**Project name**: Elm programming language
**Project link**: https://elm-lang.org/

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [x] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

Elm is a purely functional, strongly typed, reactive, and event-driven web client language.

## Citation info

* [Github homepage is here.](https://github.com/elm). For example , [`elm-core`](https://github.com/elm/core) has ~2.6k stars.
* Version history can be seen [here](https://elm-lang.org/news). The initial release (v0.1) was in April 2012, and the latest release is v0.19.1.
* The [roadmap](https://github.com/elm/projects/blob/master/roadmap.md#what-is-the-timeline) has no dates, and no mention of a v1.0.

---

**Comment by mahmoud** [comment]
That's amazing. Elm enforces SemVer for packages, but goes and does something like this. The changelog even wrote, _two years ago_:

> Elm 0.19.1 will be stable for quite some time...

**0.19** in 2019? Gotta respect the level of fortitude in resisting [calver.org](https://calver.org) and staying true to 0ver. This one might deserve its own written-up section!

Thanks! :heavy_plus_sign::zero:
