### ISSUE TITLE
Add project: pry (ruby)

### ISSUE THREAD

**Issue by jrochkind** [mahmoud/zerover#79]
Very widely used interactive debugging tool for ruby, 6300 stars

486 versions since 2010. There is a 1.0 `pre` releases from 2013 but apparently the thought to leave zerover was abandoned as hundreds of 0-releases since then. 

https://github.com/pry/pry
https://rubygems.org/gems/pry/versions

**Comment by mahmoud** [comment]
Very wise of them to have averted that c0ntingency. Excellent find, thank you!
