### ISSUE TITLE
Add project: winapi

### ISSUE THREAD

**Issue by retep998** [mahmoud/zerover#84]
## Basic info

**Project name**: winapi
**Project link**: https://github.com/retep998/winapi-rs

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [x] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

Currently used by most Rust crates that need access to Windows API.

**Comment by mahmoud** [comment]
Great find, thank y0u!
