### ISSUE TITLE
Add Project: paper.js

### ISSUE THREAD

**Issue by WesleyKapow** [mahmoud/zerover#87]
## Basic info

**Project name**: Paper.js
**Project link**: https://github.com/paperjs/paper.js
**Stars**: 12.6k
**Years**: 11 years

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [X] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [X] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [ ] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info

http://paperjs.org/about/

## Citation info

---

**Comment by mahmoud** [comment]
Nice find, thank y0u!
