### ISSUE TITLE
Add project: datasette

### ISSUE THREAD

**Issue by simonw** [mahmoud/zerover#88]
## Basic info

**Project name**: Datasette
**Project link**: https://datasette.io / https://github.com/simonw/datasette

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [ ] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Citation info

This is my project. I'm hoping to help guilt myself into finally shipping the 1.0 version!

**Comment by mahmoud** [comment]
Up on [the site](https://0ver.org/) now, for all your motivation needs. :)
