### ISSUE TITLE
Add project: knex.js

### ISSUE THREAD

**Issue by mkraeva** [mahmoud/zerover#94]
## Basic info

**Project name**: Knex.js
**Project link**: https://github.com/knex/knex

## Qualifications

[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme can obviously be used by everyone, but not every usage is
necessarily notable. Check that the first and at least one other
criterion apply:

- [x] A current ZeroVer-compliant version (`0.*`) or long history of ZeroVer usage, and
- [x] Very wide exposure (i.e., 1,000+ GitHub stars), or
- [ ] Active promotion as part of a paid product or service (e.g., Hashicorp Vault), or
- [x] Relative maturity and infrastructural importance (e.g., Compiz, docutils)

## Additional notability info
Knex.js is a popular SQL query builder for node.js. It is a dependency of several of the popular ORMs for node.js, including [objection.js](https://vincit.github.io/objection.js/) and [bookshelf.js](https://bookshelfjs.org/), which in turn are widely used in production environments.

## Citation info

---

**Comment by mahmoud** [comment]
`SELECT 0;`, great find, thanks!
